// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVeNYcyzEkuXuY1nIzzVCNR4QsVByMcfI',
    appId: '1:151612972021:web:1ca0d611d35731c6c7debc',
    messagingSenderId: '151612972021',
    projectId: 'watchhubapp-5a619',
    authDomain: 'watchhubapp-5a619.firebaseapp.com',
    storageBucket: 'watchhubapp-5a619.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZIYaG4mTQk7bXrVYRo6r571o-6eKn14I',
    appId: '1:151612972021:android:9c05cf951404780ac7debc',
    messagingSenderId: '151612972021',
    projectId: 'watchhubapp-5a619',
    storageBucket: 'watchhubapp-5a619.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBllWWgJCVHotRlGyNcOzsFo8kDvWTu88s',
    appId: '1:151612972021:ios:727e7c08e03bb4e1c7debc',
    messagingSenderId: '151612972021',
    projectId: 'watchhubapp-5a619',
    storageBucket: 'watchhubapp-5a619.appspot.com',
    androidClientId: '151612972021-7rjd6lrhjngnqcnqdcsfcvprup60knfm.apps.googleusercontent.com',
    iosClientId: '151612972021-sb3avrl5um2rol4gahraeq1nkfudd4oa.apps.googleusercontent.com',
    iosBundleId: 'com.example.watchhub',
  );
}
